//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azavar.Tools.XmlDocToMd {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MarkdownTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MarkdownTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Azavar.Tools.XmlDocToMd.MarkdownTemplates", typeof(MarkdownTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///```
        ///{0}
        ///```.
        /// </summary>
        internal static string CodeBlock {
            get {
                return ResourceManager.GetString("CodeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}]({1}).
        /// </summary>
        internal static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a name=&quot;{0}&quot;&gt;&lt;/a&gt;
        ///##### {1}
        ///
        ///{2}
        ///
        ///{3}{4}.
        /// </summary>
        internal static string MethodItem {
            get {
                return ResourceManager.GetString("MethodItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |{0}|{1}|{2}|
        ///.
        /// </summary>
        internal static string MethodParameterItem {
            get {
                return ResourceManager.GetString("MethodParameterItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.
        /// </summary>
        internal static string MethodParametersFooter {
            get {
                return ResourceManager.GetString("MethodParametersFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | Parameter | Type | Summary |
        ///|-|-|-|
        ///.
        /// </summary>
        internal static string MethodParametersHeader {
            get {
                return ResourceManager.GetString("MethodParametersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MethodsFooter {
            get {
                return ResourceManager.GetString("MethodsFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### Methods
        ///
        ///.
        /// </summary>
        internal static string MethodsHeader {
            get {
                return ResourceManager.GetString("MethodsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - [{0}]({1})
        ///
        ///.
        /// </summary>
        internal static string NamspaceItem {
            get {
                return ResourceManager.GetString("NamspaceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ### Namespaces
        ///
        ///.
        /// </summary>
        internal static string NamspacesTitle {
            get {
                return ResourceManager.GetString("NamspacesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PropertiesFooter {
            get {
                return ResourceManager.GetString("PropertiesFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #### Properties
        ///
        ///.
        /// </summary>
        internal static string PropertiesHeader {
            get {
                return ResourceManager.GetString("PropertiesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a name=&quot;{0}&quot;&gt;&lt;/a&gt;
        ///##### {1}
        ///
        ///{2}
        ///
        ///.
        /// </summary>
        internal static string PropertyItem {
            get {
                return ResourceManager.GetString("PropertyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ## {0}
        ///
        ///.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a name=&quot;{0}&quot;&gt;&lt;/a&gt;
        ///### {1}
        ///
        ///{2}
        ///
        ///{3}{4}{5}.
        /// </summary>
        internal static string TypeFormat {
            get {
                return ResourceManager.GetString("TypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |{0}|{1}|
        ///.
        /// </summary>
        internal static string TypeParameterItem {
            get {
                return ResourceManager.GetString("TypeParameterItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.
        /// </summary>
        internal static string TypeParametersFooter {
            get {
                return ResourceManager.GetString("TypeParametersFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | Type Parameter |Summary |
        ///|-|-|
        ///.
        /// </summary>
        internal static string TypeParametersHeader {
            get {
                return ResourceManager.GetString("TypeParametersHeader", resourceCulture);
            }
        }
    }
}
